name: CI/CD

on:
    push:
        branches:
            - master
            - alpha
            - beta
    pull_request:
        branches:
            - master
            - alpha
            - beta

env:
    CI: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - run: npm install

            - run: npm run test

    release:
        runs-on: ubuntu-latest
        needs:
            - test
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
        steps:
            - uses: actions/checkout@v2
              with:
                  # Pulls all commits (needed for semantic release to correctly version)
                  # See https://github.com/semantic-release/semantic-release/issues/1526
                  fetch-depth: "0"
                  persist-credentials: false

            # Pulls all tags (needed for semantic release to correctly version)
            - name: Fetch git tags
              run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - name: Use Node.js 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - run: npm install
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

            - name: Release 🚀
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
